### PR TITLE
Add IAM Roles to the request-quota-increase resources list

### PR DESCRIPTION
**Pull request by marinalimeira**
One more resource to request an increase 😄

### CODE REVIEW

**Review by brikis98 — COMMENTED** [review]
Nice!

I think you may need to update the wording in `variables.tf`.

I really wish there was a way to get all these codes in batch and add support for them...

**Comment by marinalimeira** [comment]
Updated the docs! Totally forgot about doing this...

**Comment by marinalimeira** [comment]
Could make a 30-min script that will help us to populate this array!

The `value` field makes it easier to copy this into the `examples/`.
```ruby
require 'json'

quotas = JSON.parse(`aws service-quotas list-service-quotas --service-code iam --region us-east-1
| jq '[ .Quotas[] | select(.Adjustable) ]'`)


to_update = quotas.map do |quota|
"""
# #{quota['QuotaName']}
UPDATE_KEY = {
  quota_code   = \"#{quota['QuotaCode']}\"
  service_code = \"#{quota['ServiceCode']}\"
  value        = #{quota['Value']}
},"""
end

puts to_update.join
```
Output:
```
# Customer managed policies per account
UPDATE_KEY = {
  quota_code   = "L-E95E4862"
  service_code = "iam"
  value        = 1500
},
# Groups per account
UPDATE_KEY = {
  quota_code   = "L-F4A5425F"
  service_code = "iam"
  value        = 300
},
# Instance profiles per account
UPDATE_KEY = {
  quota_code   = "L-6E65F664"
  service_code = "iam"
  value        = 1000
},
# Managed policies per role
UPDATE_KEY = {
  quota_code   = "L-0DA4ABF3"
  service_code = "iam"
  value        = 10
},
# Managed policies per user
UPDATE_KEY = {
  quota_code   = "L-4019AD8B"
  service_code = "iam"
  value        = 10
},
# Role trust policy length
UPDATE_KEY = {
  quota_code   = "L-C07B4B0D"
  service_code = "iam"
  value        = 2048
},
# Roles per account
UPDATE_KEY = {
  quota_code   = "L-FE177D64"
  service_code = "iam"
  value        = 1000
},
# Server certificates per account
UPDATE_KEY = {
  quota_code   = "L-BF35879D"
  service_code = "iam"
  value        = 20
},
```

We need to do this for every service...

**Comment by marinalimeira** [comment]
Also, the build is broken due to some error on `pip install`. I will take a look at this next week...

**Comment by brikis98** [comment]
> Could make a 30-min script that will help us to populate this array!
> 
> The `value` field makes it easier to copy this into the `examples/`.
> 
> ```ruby
> require 'json'
> 
> quotas = JSON.parse(`aws service-quotas list-service-quotas --service-code iam --region us-east-1
> | jq '[ .Quotas[] | select(.Adjustable) ]'`)
> 
> 
> to_update = quotas.map do |quota|
> """
> # #{quota['QuotaName']}
> UPDATE_KEY = {
>   quota_code   = \"#{quota['QuotaCode']}\"
>   service_code = \"#{quota['ServiceCode']}\"
>   value        = #{quota['Value']}
> },"""
> end
> 
> puts to_update.join
> ```
> 
> Output:
> 
> ```
> # Customer managed policies per account
> UPDATE_KEY = {
>   quota_code   = "L-E95E4862"
>   service_code = "iam"
>   value        = 1500
> },
> # Groups per account
> UPDATE_KEY = {
>   quota_code   = "L-F4A5425F"
>   service_code = "iam"
>   value        = 300
> },
> # Instance profiles per account
> UPDATE_KEY = {
>   quota_code   = "L-6E65F664"
>   service_code = "iam"
>   value        = 1000
> },
> # Managed policies per role
> UPDATE_KEY = {
>   quota_code   = "L-0DA4ABF3"
>   service_code = "iam"
>   value        = 10
> },
> # Managed policies per user
> UPDATE_KEY = {
>   quota_code   = "L-4019AD8B"
>   service_code = "iam"
>   value        = 10
> },
> # Role trust policy length
> UPDATE_KEY = {
>   quota_code   = "L-C07B4B0D"
>   service_code = "iam"
>   value        = 2048
> },
> # Roles per account
> UPDATE_KEY = {
>   quota_code   = "L-FE177D64"
>   service_code = "iam"
>   value        = 1000
> },
> # Server certificates per account
> UPDATE_KEY = {
>   quota_code   = "L-BF35879D"
>   service_code = "iam"
>   value        = 20
> },
> ```
> 
> We need to do this for every service...

Ah, neat. I'd be in favor of a time-boxed experiment to see if you can get that working!

**Comment by marinalimeira** [comment]
Closing this PR because of #39.

**Pull request closed without merging**
