### PR TITLE
Restrict provider version.

### PR DESCRIPTION
**Pull request by rhoboat**
Uses https://github.com/gruntwork-io/prototypes/compare/feature/aws4-lock?expand=1 and https://github.com/rhoboat/tfupdate/tree/feature/aws-version-addon to lock the AWS provider to < 4.0.

### CODE REVIEW

**Review by yorinasub17 — COMMENTED** [review]
Ah, we should only add this for the modules in this repo that use the `aws` provider. Otherwise, we force terraform to load the `aws` provider when it doesn't need to.

I think the only modules that should have this are `request-quota-increase` and `instance-type` modules.

**Review by yorinasub17 — APPROVED** [review]
Modules LGTM, but nit: we should do the same for the examples as well. Going to approve this since it's not as big a deal (since the users won't be affected), but something we should address for cleanliness.

**Comment by rhoboat** [comment]
Removed the change from examples! 🙏

**Review by yorinasub17 — APPROVED** [review]
Updates LGTM!

**Comment by rhoboat** [comment]
Rerunning tests.

**Comment by rhoboat** [comment]
This repo has some branches where the build is failing. I am trying to resolve this.

**Review by yorinasub17 — APPROVED** [review]

**Pull request merged**
