### PR TITLE
Modernize circleci implementation

### PR DESCRIPTION
**Pull request by yorinasub17**
In the process, fix the build.

### CODE REVIEW

**Comment by rhoboat** [comment]
To fix this, what repo(s) did you use as an example to start from?

**Comment by rhoboat** [comment]
I see that the build is running a couple more times now, but I saw the passing build, so I'm going to approve this.

**Review by rhoboat — APPROVED** [review]

**Comment by yorinasub17** [comment]
> To fix this, what repo(s) did you use as an example to start from?

I used `terraform-aws-eks`, but then bumped a few versions (e.g., the machine image and python docker image).

**Comment by yorinasub17** [comment]
Ah the latest build failed due to concurrency issue with request quota increase, but I also see a bug where `resource_class: small` is not valid for machine executors. I updated this to `medium`!

**Review by rhoboat — APPROVED** [review]

**Pull request merged**
